# Generated by Django 3.2.6 on 2022-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
    ]
